testproject-postgresql:
  container_name: testproject-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/TestProject/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=TestProject
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
